### ISSUE TITLE
Dependabot needs to also update pypoetry.toml file

### ISSUE THREAD

**Issue by ltorres6** [OSIPI/osipi#64]
### Feature description

Currently, dependabot only updates the lock file.

### Describe the solution

This might be solved using a dependabot configuration file at the root level.

### Are you working on this?

None

**Comment by lambaaryan011** [comment]
@ltorres6  o love to solve this issue can you assign me this

**Comment by div-dev123** [comment]
@ltorres6  I’ve prepared a basic version of the .dependabot.yml file that addresses the problem of Dependabot only updating the lock file. I can further refine it if needed with your input . Please tell me if i can create a PR!

thanks!

**Comment by rahulcse129** [comment]
@ltorres6 Does this issue is still open for work?

**Comment by Devguru-codes** [comment]
Hello, @ltorres6 
I have a plan to implement this feature. I am working on this and soon will make a PR (I will make PR only when you will confirm the plan of action). 
Plan -  Add Dependabot configuration to manage Python and GitHub Actions dependency updates

## Location
`.github/dependabot.yml` — NEW FILE

## Description
Currently, Dependabot is not configured with a `dependabot.yml` file. Without this file, GitHub's Dependabot can only update the lock file (default behavior) and cannot open pull requests for updated Python packages or GitHub Actions versions. The project has:
- **12+ Python dependencies** in `pyproject.toml` (numpy, scipy, pytest, mkdocs, etc.)
- **12+ GitHub Actions** across 4 workflows, many pinned to outdated versions (@v3)

Without a config file, Dependabot cannot proactively manage these.

## Reproduction (on `main` branch)

### Library Integration Output (on `main`)
```
=== Dependabot Configuration Analysis ===

  .github/dependabot.yml exists: False

=== GitHub Actions in Use ===

  documentation.yaml:
    Line 17: uses: actions/checkout@v3
    Line 22: uses: actions/setup-python@v4
    Line 27: uses: Gr1N/setup-poetry@v8
    Line 39: uses: peaceiris/actions-gh-pages@v3
  pre-commit.yaml:
    Line 13: - uses: actions/checkout@v3
    Line 16: uses: actions/setup-python@v3
    Line 21: uses: Gr1N/setup-poetry@v8
    Line 26: uses: actions/cache@v3
  pytest-actions.yaml:
    Line 16: - uses: actions/checkout@v3
    Line 19: uses: actions/setup-python@v4
    Line 24: uses: actions/setup-java@v3
    Line 31: uses: Gr1N/setup-poetry@v8
    Line 36: uses: actions/cache@v3
    Line 56: uses: codecov/codecov-action@v3
  release.yaml:
    Line 38: uses: actions/checkout@v3
    Line 41: uses: actions/setup-python@v4
    Line 46: uses: Gr1N/setup-poetry@v8
    Line 67: uses: release-drafter/release-drafter@v6
    Line 80: uses: actions/create-release@v1
    Line 95: uses: pypa/gh-action-pypi-publish@release/v1

>> VERDICT: Feature is MISSING. No dependabot.yml — Dependabot cannot manage deps.
```

### Automated Results on `main` branch

| # | Test | Status | Detail |
|---|------|--------|--------|
| 1 | .github/dependabot.yml exists | FAIL | No dependabot.yml |
| 2 | pyproject.toml has dependencies Dependabot should manage | PASS | |
| 3 | Found 20 GitHub Actions with pinned versions | PASS | |
| 4 | No outdated GitHub Action versions (@v3) | FAIL | Found 6+ outdated actions |

**Summary: PASSED=2 FAILED=2**

---

## Suggested Fix (for maintainer review)

**Recommendation:** Add `.github/dependabot.yml` with two package ecosystems:

### 1. `pip` — Python dependency updates
- Reads `pyproject.toml` to detect Python dependencies
- Schedule: weekly on Mondays
- Creates PRs like: `build(deps): bump numpy from 1.21.2 to 1.26.4`
- Limit: 10 open PRs max

### 2. `github-actions` — Workflow action version updates
- Scans all `.github/workflows/*.yml` files for `uses:` directives
- Schedule: weekly on Mondays
- Creates PRs like: `ci(deps): bump actions/checkout from 3 to 4`
- Limit: 5 open PRs max

### Proposed `dependabot.yml`:
```yaml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
    commit-message:
      prefix: "build"
      include: "scope"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
    commit-message:
      prefix: "ci"
      include: "scope"
```

### Why this approach:
1. `pip` ecosystem reads `pyproject.toml` natively — no need to create a separate `requirements.txt`
2. Commit message prefixes (`build`, `ci`) are compatible with conventional commits used in the release-drafter
3. Labels allow easy filtering in the PR list
4. The `open-pull-requests-limit` prevents Dependabot from flooding the repo with PRs
5. Weekly schedule is the standard cadence for scientific Python projects

### What happens after merging:
- Dependabot will immediately scan dependencies and actions
- Within a few days, it will open PRs for any outdated dependencies
- This includes bumping `actions/checkout` from @v3 → @v4, `actions/setup-python` from @v3/@v4 → @v5, etc.
- For Python deps, it will respect the version constraints in `pyproject.toml` (e.g., `^1.21.2` allows `1.x` updates)
